/**
 * SignalR method names, mirroring `src/Protocol/Hub/HubMethods.cs`.
 *
 * The C# side shares one file between the agent and the hub, so those two cannot
 * drift. This file is the third copy, and the only one no compiler can check
 * against the others — `wire.contract.test.ts` reads a fixture generated by the C#
 * tests to catch it if it does.
 */

/** Methods this client invokes on the hub. */
export const Server = {
  ClientHandshake: 'ClientHandshake',
  ListMachines: 'ListMachines',
  AttachSession: 'AttachSession',
  DetachSession: 'DetachSession',
  SendInput: 'SendInput',
  BeginTerminalUpload: 'BeginTerminalUpload',
  UploadTerminalChunk: 'UploadTerminalChunk',
  CancelTerminalUpload: 'CancelTerminalUpload',
  ResizeTerminal: 'ResizeTerminal',
  InterruptSession: 'InterruptSession',
  SendChatMessage: 'SendChatMessage',
  RespondChatPermission: 'RespondChatPermission',
  SetSessionType: 'SetSessionType',
  SetSessionName: 'SetSessionName',
  SetSessionPinned: 'SetSessionPinned',
  RegisterPush: 'RegisterPush',
  RefreshToken: 'RefreshToken',
  ListProjects: 'ListProjects',
  CreateProject: 'CreateProject',
  UpdateProject: 'UpdateProject',
  DeleteProject: 'DeleteProject',
  SetSessionProject: 'SetSessionProject',
} as const

/** Methods the hub invokes on this client. */
export const Client = {
  MachineList: 'MachineList',
  MachineOnline: 'MachineOnline',
  MachineOffline: 'MachineOffline',
  SessionOpened: 'SessionOpened',
  SessionUpdated: 'SessionUpdated',
  SessionClosed: 'SessionClosed',
  TerminalOutput: 'TerminalOutput',
  SessionAwaitingInput: 'SessionAwaitingInput',
  SessionAttention: 'SessionAttention',
  ChatTranscript: 'ChatTranscript',
  TokenExpiring: 'TokenExpiring',
  Error: 'Error',
  ProjectCreated: 'ProjectCreated',
  ProjectUpdated: 'ProjectUpdated',
  ProjectDeleted: 'ProjectDeleted',
} as const

/** Must match `ProtocolVersion.Current`. */
export const PROTOCOL_VERSION = 4
