import { describe, expect, it } from 'vitest'
import { decode } from '@msgpack/msgpack'

import fixture from './wire.fixture.json'
import { PROTOCOL_VERSION } from './methods'
import {
  decodeAwaitingInput,
  decodeChatAttachmentReply,
  decodeChatPromptReply,
  decodeChatTranscript,
  decodeError,
  decodeMachineList,
  decodeMachineOffline,
  decodeMachineOnline,
  decodeProject,
  decodeProjectDeleted,
  decodeProjectList,
  decodeProjectNotification,
  decodeProjectResult,
  decodeSessionClosed,
  decodeSessionOpened,
  decodeSessionAttention,
  decodeSessionUpdated,
  decodeTerminalUploadReply,
  decodeTerminalOutput,
  decodeTokenExpiring,
  encodeAttachSession,
  encodeBeginChatAttachment,
  encodeBeginTerminalUpload,
  encodeCancelChatAttachment,
  encodeCancelTerminalUpload,
  encodeChatAttachmentChunk,
  encodeClientHandshake,
  encodeCreateProject,
  encodeDeleteProject,
  encodeDetachSession,
  encodeInterruptSession,
  encodeRegisterPush,
  encodeRespondChatPermission,
  encodeResizeTerminal,
  encodeSendInput,
  encodeSendChatMessage,
  encodeSendChatPrompt,
  encodeSetSessionName,
  encodeSetSessionPinned,
  encodeSetSessionProject,
  encodeSetSessionType,
  encodeTerminalUploadChunk,
  encodeUpdateProject,
  type CliType,
} from './wire'

/**
 * The decoder against bytes the C# serializer actually produced.
 *
 * `wire.fixture.json` is generated by `tests/Protocol.Tests/WireContractTests.cs`,
 * which records both the bytes and the values they carry. Nothing here hand-copies
 * a constant from the C# side: every expectation is read out of the fixture's own
 * `decoded` block, so if a message's field order changes, the C# test fails on the
 * bytes and these fail on the values.
 */

type FixtureMessage = { type: string; base64: string; decoded: Record<string, unknown> }

const messages = fixture.messages as unknown as Record<string, FixtureMessage>

function wire(name: string): unknown {
  const entry = messages[name]
  expect(entry, `${name} is missing from the wire fixture`).toBeDefined()

  return decode(Uint8Array.from(atob(entry.base64), (c) => c.charCodeAt(0)))
}

function expected(name: string): Record<string, any> {
  return messages[name].decoded
}

describe('the fixture itself', () => {
  it('was generated for the protocol version this build speaks', () => {
    // A fixture from a different protocol version would make every test below pass
    // against the wrong contract, which is worse than having no tests.
    expect(fixture.protocolVersion).toBe(PROTOCOL_VERSION)
  })
})

describe('decoding what the hub sends', () => {
  it('reads a machine list, including a machine with no sessions', () => {
    const machines = decodeMachineList(wire('machineList'))
    const want = expected('machineList').machines as any[]

    expect(machines).toHaveLength(want.length)

    machines.forEach((machine, i) => {
      expect(machine.machineId).toBe(want[i].machineId)
      expect(machine.displayName).toBe(want[i].displayName)
      expect(machine.os).toBe(want[i].os)
      expect(machine.agentVersion).toBe(want[i].agentVersion)
      expect(machine.online).toBe(want[i].online)
      expect(machine.sessions).toHaveLength(want[i].sessions.length)
    })
  })

  it('reads a session, including its arguments and working directory', () => {
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0]

    expect(session.sessionId).toBe(want.sessionId)
    expect(session.program).toBe(want.program)
    expect(session.args).toEqual(want.args)
    expect(session.cwd).toBe(want.cwd)
    expect(session.cols).toBe(want.cols)
    expect(session.rows).toBe(want.rows)
    expect(session.displayName).toBe(want.displayName)
    expect(session.awaitingInput).toBe(want.awaitingInput)
    expect(session.suggestedProjectId).toBe(want.suggestedProjectId)
    expect(session.suggestedProjectMoves).toBe(want.suggestedProjectMoves)
  })

  /**
   * The C# side renders the enum as a number in the fixture's `decoded` block —
   * that is `System.Text.Json` describing a C# enum, not what MessagePack put on the
   * wire. The bytes carry the *name*, which is what the decoder has to read, so this
   * asserts the name and cross-checks the ordinal the C# enum declares.
   */
  it('reads the CLI type as the name the wire actually carries', () => {
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]

    expect(session.cliType).toBe('ClaudeCode')
    expect(expected('machineList').machines[0].sessions[0].cliType).toBe(3)
  })

  it('distinguishes structured agent chats from terminals', () => {
    const sessions = decodeMachineList(wire('machineList'))[0].sessions

    expect(sessions[0].kind).toBe('Terminal')
    expect(sessions[1].kind).toBe('AgentChat')
    expect(sessions[1].program).toBe('GitHub Copilot')
  })

  it('calls a session Generic when the type is missing or unknown', () => {
    // A version 1 agent sends a nine-element session; a later one could send a type
    // this build has never heard of. Both mean "nobody has said", not a crash.
    const raw = wire('sessionOpened') as unknown[]
    const session = raw[1] as unknown[]

    expect(decodeSessionOpened([raw[0], session.slice(0, 9)]).session.cliType).toBe('Generic')
    expect(
      decodeSessionOpened([raw[0], [...session.slice(0, 9), 'Emacs']]).session.cliType,
    ).toBe('Generic')
  })

  it('reads a session being corrected', () => {
    const updated = decodeSessionUpdated(wire('sessionUpdated'))
    const want = expected('sessionUpdated')

    expect(updated.machineId).toBe(want.machineId)
    expect(updated.session.sessionId).toBe(want.session.sessionId)
    expect(updated.session.cliType).toBe('CopilotCli')
  })

  it('reads the name the user gave a session, and whether they pinned it', () => {
    const updated = decodeSessionUpdated(wire('sessionUpdated'))
    const want = expected('sessionUpdated')

    expect(updated.session.customName).toBe(want.session.customName)
    expect(updated.session.pinned).toBe(want.session.pinned)
  })

  it('treats a session from a hub that predates renaming as unnamed and unpinned', () => {
    // The two fields were appended, so an older hub sends a ten-element session.
    // Reading past the end has to land on "nobody renamed it", not on undefined
    // reaching a row that then renders the string "undefined".
    const raw = wire('sessionUpdated') as unknown[]
    const session = raw[1] as unknown[]

    const decoded = decodeSessionUpdated([raw[0], session.slice(0, 10)]).session

    expect(decoded.customName).toBeNull()
    expect(decoded.pinned).toBe(false)
  })

  it('recovers the real instant a session started, not the sender wall clock', () => {
    // The fixture deliberately uses a +03:00 offset. A decoder that reads only the
    // first element of the DateTimeOffset pair passes on a UTC machine and is three
    // hours wrong here.
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0].startedAt as string

    expect(session.startedAt.toISOString()).toBe(new Date(want).toISOString())
  })

  it('falls back to the program name when a session has no display name', () => {
    const { session } = decodeSessionOpened(wire('sessionOpened'))

    expect(expected('sessionOpened').session.displayName).toBeNull()
    expect(session.displayName).toBe('pwsh')
  })

  it('reads a machine coming online', () => {
    const machine = decodeMachineOnline(wire('machineOnline'))

    expect(machine.machineId).toBe(expected('machineOnline').machine.machineId)
    expect(machine.online).toBe(true)
    expect(machine.sessions).toEqual([])
  })

  it('reads a machine going offline', () => {
    expect(decodeMachineOffline(wire('machineOffline'))).toBe(
      expected('machineOffline').machineId,
    )
  })

  it('reads a session opening', () => {
    const opened = decodeSessionOpened(wire('sessionOpened'))
    const want = expected('sessionOpened')

    expect(opened.machineId).toBe(want.machineId)
    expect(opened.session.sessionId).toBe(want.session.sessionId)
    expect(opened.session.args).toEqual([])
  })

  it('reads a session closing, with its exit code', () => {
    const closed = decodeSessionClosed(wire('sessionClosed'))
    const want = expected('sessionClosed')

    expect(closed.machineId).toBe(want.machineId)
    expect(closed.sessionId).toBe(want.sessionId)
    expect(closed.exitCode).toBe(want.exitCode)
  })

  it('reads terminal output, keeping the bytes exactly as sent', () => {
    const output = decodeTerminalOutput(wire('terminalOutput'))
    const want = expected('terminalOutput')

    expect(output.sessionId).toBe(want.sessionId)
    expect(output.seq).toBe(want.seq)
    // The enum travels as its name. A decoder that expects a number reads every
    // snapshot as a delta and never clears the screen.
    expect(output.kind).toBe('Snapshot')
    expect(Array.from(output.data)).toEqual([0x1b, 0x5b, 0x32, 0x4a, 0x68, 0x69, 0x0d, 0x0a])
    expect(output.continuityLost).toBe(true)
  })

  it('falls back to sequence inference for output from an older agent', () => {
    expect(decodeTerminalOutput(['session-1', 7, 'Snapshot', new Uint8Array()]).continuityLost).toBeNull()
  })

  it('reads a sequence number well past 32 bits', () => {
    // Long-running sessions overflow an int, and a decoder that truncates would
    // silently reorder output.
    expect(decodeTerminalOutput(wire('terminalOutput')).seq).toBe(4294967297)
  })

  it('reads an awaiting-input notice and its hint', () => {
    const awaiting = decodeAwaitingInput(wire('sessionAwaitingInput'))
    const want = expected('sessionAwaitingInput')

    expect(awaiting.machineId).toBe(want.machineId)
    expect(awaiting.sessionId).toBe(want.sessionId)
    expect(awaiting.hint).toBe(want.hint)
  })

  it('reads explicit attention state', () => {
    const attention = decodeSessionAttention(wire('sessionAttention'))
    const want = expected('sessionAttention')

    expect(attention.machineId).toBe(want.machineId)
    expect(attention.sessionId).toBe(want.sessionId)
    expect(attention.awaitingInput).toBe(true)
    expect(attention.hint).toBe(want.hint)
  })

  it('reads typed transcript events and permission options', () => {
    const transcript = decodeChatTranscript(wire('chatTranscript'))
    const want = expected('chatTranscript')

    expect(transcript.sessionId).toBe(want.sessionId)
    expect(transcript.seq).toBe(want.seq)
    expect(transcript.kind).toBe('Snapshot')
    expect(transcript.events.map((event) => event.kind)).toEqual([
      'UserMessage',
      'AgentThought',
      'ToolCall',
      'Plan',
      'Permission',
      'Permission',
    ])
    expect(transcript.events[2].content[0]).toMatchObject({
      type: 'diff',
      path: 'tests/ExampleTests.cs',
    })
    expect(transcript.events[2].locations).toEqual([
      { path: 'tests/ExampleTests.cs', line: 42 },
    ])
    expect(transcript.events[3].planEntries[1]).toEqual({
      content: 'Run the tests',
      priority: 'medium',
      status: 'in_progress',
    })
    expect(transcript.events[4].permissionRequestId).toBe('req-1')
    expect(transcript.events[4].options).toEqual([
      { optionId: 'allow-once', name: 'Allow once', kind: 'allow_once' },
      { optionId: 'reject-once', name: 'Deny', kind: 'reject_once' },
    ])
    expect(transcript.events[5].options[1].name).toBe('SQLite')
  })

  it('reads a token expiry', () => {
    const expiresAt = decodeTokenExpiring(wire('tokenExpiring'))

    expect(expiresAt.toISOString()).toBe(
      new Date(expected('tokenExpiring').expiresAt as string).toISOString(),
    )
  })

  it('reads an error, and its null session id', () => {
    const error = decodeError(wire('error'))
    const want = expected('error')

    expect(error.code).toBe(want.code)
    expect(error.message).toBe(want.message)
    expect(error.sessionId).toBeNull()
  })

  it('reads a session opened with a non-General project already assigned', () => {
    const opened = decodeSessionOpened(wire('sessionOpenedWithProject'))
    const want = expected('sessionOpenedWithProject')

    expect(opened.session.projectId).toBe(want.session.projectId)
  })

  it('reads disk-confirmed terminal upload progress', () => {
    const reply = decodeTerminalUploadReply(wire('terminalUploadReply'))
    const want = expected('terminalUploadReply')

    expect(reply.uploadId).toBe(want.uploadId)
    expect(reply.confirmedBytes).toBe(want.confirmedBytes)
    expect(reply.totalBytes).toBe(want.totalBytes)
    expect(reply.remotePath).toBeNull()
    expect(reply.errorCode).toBeNull()
  })

  it('reads staged chat attachment progress, which never carries a path', () => {
    const reply = decodeChatAttachmentReply(wire('chatAttachmentReply'))
    const want = expected('chatAttachmentReply')

    expect(reply.attachmentId).toBe(want.attachmentId)
    expect(reply.confirmedBytes).toBe(want.confirmedBytes)
    expect(reply.totalBytes).toBe(want.totalBytes)
    expect(reply.completed).toBe(false)
    expect(reply.errorCode).toBeNull()
    expect(Object.keys(reply)).not.toContain('remotePath')
  })

  it('reads a prompt acknowledgement', () => {
    const reply = decodeChatPromptReply(wire('chatPromptReply'))

    expect(reply.accepted).toBe(true)
    expect(reply.errorCode).toBeNull()
  })

  it('reads negotiated chat capabilities off an updated session', () => {
    const updated = decodeSessionUpdated(wire('chatSessionUpdatedWithCapabilities'))

    expect(updated.session.kind).toBe('AgentChat')
    expect(updated.session.chatCapabilities).toEqual({ image: true, embeddedContext: true })
  })

  it('treats a chat session from an agent that predates attachments as unable to take them', () => {
    // ChatCapabilities was appended after ProjectId, so a version 5 agent sends a
    // fourteen-element session. Reading past the end has to land on null — "no
    // attachment support" — rather than on an object the composer would trust.
    const raw = wire('chatSessionUpdatedWithCapabilities') as unknown[]
    const session = raw[1] as unknown[]

    expect(decodeSessionUpdated([raw[0], session.slice(0, 14)]).session.chatCapabilities).toBeNull()
  })

  it('treats a session from a hub that predates projects as General', () => {
    // ProjectId was appended after Kind, so a version 3 hub that only knows
    // about ACP sends a thirteen-element session (through Kind). Reading past
    // the end has to land on General (null), not on undefined.
    const raw = wire('sessionOpenedWithProject') as unknown[]
    const session = raw[1] as unknown[]

    expect(decodeSessionOpened([raw[0], session.slice(0, 13)]).session.projectId).toBeNull()
  })

  it('reads a project, including its icon version', () => {
    const projects = decodeProjectList(wire('projectList'))
    const want = expected('projectList').projects as any[]

    expect(projects).toHaveLength(want.length)

    projects.forEach((project, i) => {
      expect(project.projectId).toBe(want[i].projectId)
      expect(project.name).toBe(want[i].name)
      expect(project.description).toBe(want[i].description)
      expect(project.siteUrl).toBe(want[i].siteUrl)
      expect(project.repoUrl).toBe(want[i].repoUrl)
      expect(project.isGeneral).toBe(want[i].isGeneral)
      expect(project.iconVersion).toBe(want[i].iconVersion)
    })
  })

  it('reads General first in the project list, since the hub always seeds it', () => {
    const projects = decodeProjectList(wire('projectList'))
    expect(projects[0].isGeneral).toBe(true)
  })

  it('reads a successful ProjectResult, with no error', () => {
    const result = decodeProjectResult(wire('projectResult'))
    const want = expected('projectResult').project

    expect(result.project?.projectId).toBe(want.projectId)
    expect(result.project?.name).toBe(want.name)
    expect(result.error).toBeNull()
  })

  it('reads a failed ProjectResult, with no project', () => {
    const result = decodeProjectResult(wire('projectResultError'))
    const want = expected('projectResultError')

    expect(result.project).toBeNull()
    expect(result.error).toBe(want.error)
  })

  it('reads a project created for another device to pick up', () => {
    const project = decodeProjectNotification(wire('projectCreated'))
    expect(project.projectId).toBe(expected('projectCreated').project.projectId)
  })

  it('reads a project updated, including a bumped icon version', () => {
    const project = decodeProjectNotification(wire('projectUpdated'))
    const want = expected('projectUpdated').project

    expect(project.projectId).toBe(want.projectId)
    expect(project.iconVersion).toBe(want.iconVersion)
  })

  it('reads a project deleted, as a bare id', () => {
    expect(decodeProjectDeleted(wire('projectDeleted'))).toBe(expected('projectDeleted').projectId)
  })

  it('decodes one ProjectInfo directly, matching what the list decodes', () => {
    const [first] = (wire('projectList') as unknown[])[0] as unknown[]
    const project = decodeProject(first)
    const want = expected('projectList').projects[0]

    expect(project.projectId).toBe(want.projectId)
    expect(project.name).toBe(want.name)
  })
})

describe('encoding what we send the hub', () => {
  // Encoding is checked against the same fixture from the other direction: the C#
  // test recorded the bytes its own deserialiser accepts, so producing the same
  // array shape is the whole requirement. A JS object here would encode as a
  // MessagePack map, which the C# formatter for a keyed type cannot read at all.

  function shape(name: string): unknown[] {
    const value = wire(name)
    expect(Array.isArray(value)).toBe(true)
    return value as unknown[]
  }

  it('sends a handshake the hub can read', () => {
    const [version, client] = shape('clientHandshakeRequest')

    expect(encodeClientHandshake(version as number, client as string)).toEqual([version, client])
    expect(version).toBe(PROTOCOL_VERSION)
  })

  it('sends an attach request, including a null last sequence', () => {
    const want = shape('attachSessionRequest')

    expect(encodeAttachSession(want[0] as string, want[1] as string, 80, 24, null)).toEqual(want)
  })

  it('sends a detach request', () => {
    const want = shape('detachSessionRequest')

    expect(encodeDetachSession(want[0] as string)).toEqual(want)
  })

  it('sends input as raw bytes', () => {
    const want = shape('sendInputRequest')

    const encoded = encodeSendInput(want[0] as string, new Uint8Array([0x64, 0x69, 0x72, 0x0d]))

    expect(encoded[0]).toBe(want[0])
    expect(Array.from(encoded[1] as Uint8Array)).toEqual(Array.from(want[1] as Uint8Array))
  })

  it('starts a bounded terminal upload', () => {
    const want = shape('beginTerminalUploadRequest')

    expect(
      encodeBeginTerminalUpload(
        want[0] as string,
        want[1] as string,
        want[2] as string,
        want[3] as number,
      ),
    ).toEqual(want)
  })

  it('sends an ordered upload chunk as raw bytes', () => {
    const want = shape('terminalUploadChunkRequest')
    const encoded = encodeTerminalUploadChunk(
      want[0] as string,
      want[1] as string,
      want[2] as number,
      new Uint8Array([0x00, 0x7f, 0x80, 0xff]),
    )

    expect(encoded.slice(0, 3)).toEqual(want.slice(0, 3))
    expect(Array.from(encoded[3] as Uint8Array)).toEqual(Array.from(want[3] as Uint8Array))
  })

  it('cancels a partial terminal upload', () => {
    const want = shape('cancelTerminalUploadRequest')
    expect(encodeCancelTerminalUpload(want[0] as string, want[1] as string)).toEqual(want)
  })

  it('sends a resize', () => {
    const want = shape('resizeTerminalRequest')

    expect(encodeResizeTerminal(want[0] as string, want[1] as number, want[2] as number)).toEqual(
      want,
    )
  })

  it('sends an interrupt', () => {
    const want = shape('interruptSessionRequest')

    expect(encodeInterruptSession(want[0] as string)).toEqual(want)
  })

  it('sends a structured chat message', () => {
    const want = shape('sendChatMessageRequest')

    expect(encodeSendChatMessage(want[0] as string, want[1] as string)).toEqual(want)
  })

  it('starts a bounded chat attachment, carrying the browser-declared type', () => {
    const want = shape('beginChatAttachmentRequest')

    expect(
      encodeBeginChatAttachment(
        want[0] as string,
        want[1] as string,
        want[2] as string,
        want[3] as string,
        want[4] as number,
      ),
    ).toEqual(want)
  })

  it('sends an ordered chat attachment chunk as raw bytes', () => {
    const want = shape('chatAttachmentChunkRequest')
    const encoded = encodeChatAttachmentChunk(
      want[0] as string,
      want[1] as string,
      want[2] as number,
      new Uint8Array([0x00, 0x7f, 0x80, 0xff]),
    )

    expect(encoded.slice(0, 3)).toEqual(want.slice(0, 3))
    expect(Array.from(encoded[3] as Uint8Array)).toEqual(Array.from(want[3] as Uint8Array))
  })

  it('removes a staged chat attachment', () => {
    const want = shape('cancelChatAttachmentRequest')
    expect(encodeCancelChatAttachment(want[0] as string, want[1] as string)).toEqual(want)
  })

  it('sends a prompt of text plus staged attachment ids', () => {
    const want = shape('sendChatPromptRequest')

    expect(
      encodeSendChatPrompt(want[0] as string, want[1] as string, want[2] as string[]),
    ).toEqual(want)
  })

  it('sends a permission response', () => {
    const want = shape('respondChatPermissionRequest')

    expect(
      encodeRespondChatPermission(want[0] as string, want[1] as string, want[2] as string),
    ).toEqual(want)
  })

  it('sends a type correction as the name the hub validates', () => {
    const want = shape('setSessionTypeRequest')

    expect(want[1]).toBe('ClaudeCode')
    expect(encodeSetSessionType(want[0] as string, want[1] as CliType)).toEqual(want)
  })

  it('sends a rename, machine id first', () => {
    const want = shape('setSessionNameRequest')

    expect(encodeSetSessionName(want[0] as string, want[1] as string, want[2] as string)).toEqual(
      want,
    )
  })

  it('sends a cleared name as null, not as an empty string', () => {
    // The difference is the whole feature: null reveals the agent's own name again,
    // an empty string would leave the row with nothing to show.
    const want = shape('setSessionNameClearRequest')

    expect(want[2]).toBeNull()
    expect(encodeSetSessionName(want[0] as string, want[1] as string, null)).toEqual(want)
  })

  it('sends a pin', () => {
    const want = shape('setSessionPinnedRequest')

    expect(encodeSetSessionPinned(want[0] as string, want[1] as string, want[2] as boolean)).toEqual(
      want,
    )
  })

  it('sends per-device push category preferences as disabled flags', () => {
    expect(encodeRegisterPush('endpoint', 'p256dh', 'auth', true, false, true)).toEqual([
      'endpoint',
      ['p256dh', 'auth'],
      true,
      false,
      true,
    ])
  })

  it('sends a move to a project', () => {
    const want = shape('setSessionProjectRequest')

    expect(
      encodeSetSessionProject(
        want[0] as string,
        want[1] as string,
        want[2] as string,
        'Suggested',
      ),
    ).toEqual(want)
  })

  it('sends a move back to General as null, not the string "general"', () => {
    const want = shape('setSessionProjectClearRequest')

    expect(want[2]).toBeNull()
    expect(encodeSetSessionProject(want[0] as string, want[1] as string, null)).toEqual(want)
  })

  it('sends a project creation with every optional field filled in', () => {
    const want = shape('createProjectRequest')

    expect(
      encodeCreateProject(
        want[0] as string,
        want[1] as string,
        want[2] as string,
        want[3] as string,
      ),
    ).toEqual(want)
  })

  it('sends a project update, id first', () => {
    const want = shape('updateProjectRequest')

    expect(
      encodeUpdateProject(
        want[0] as string,
        want[1] as string,
        want[2] as string,
        want[3] as string,
        want[4] as string,
      ),
    ).toEqual(want)
  })

  it('sends a project deletion', () => {
    const want = shape('deleteProjectRequest')

    expect(encodeDeleteProject(want[0] as string)).toEqual(want)
  })
})
