import { describe, expect, it } from 'vitest'
import { decode } from '@msgpack/msgpack'

import fixture from './wire.fixture.json'
import { PROTOCOL_VERSION } from './methods'
import {
  decodeAwaitingInput,
  decodeChatTranscript,
  decodeError,
  decodeMachineList,
  decodeMachineOffline,
  decodeMachineOnline,
  decodeSessionClosed,
  decodeSessionOpened,
  decodeSessionAttention,
  decodeSessionUpdated,
  decodeTerminalOutput,
  decodeTokenExpiring,
  encodeAttachSession,
  encodeClientHandshake,
  encodeDetachSession,
  encodeInterruptSession,
  encodeRespondChatPermission,
  encodeResizeTerminal,
  encodeSendInput,
  encodeSendChatMessage,
  encodeSetSessionName,
  encodeSetSessionPinned,
  encodeSetSessionType,
  type CliType,
} from './wire'

/**
 * The decoder against bytes the C# serializer actually produced.
 *
 * `wire.fixture.json` is generated by `tests/Protocol.Tests/WireContractTests.cs`,
 * which records both the bytes and the values they carry. Nothing here hand-copies
 * a constant from the C# side: every expectation is read out of the fixture's own
 * `decoded` block, so if a message's field order changes, the C# test fails on the
 * bytes and these fail on the values.
 */

type FixtureMessage = { type: string; base64: string; decoded: Record<string, unknown> }

const messages = fixture.messages as unknown as Record<string, FixtureMessage>

function wire(name: string): unknown {
  const entry = messages[name]
  expect(entry, `${name} is missing from the wire fixture`).toBeDefined()

  return decode(Uint8Array.from(atob(entry.base64), (c) => c.charCodeAt(0)))
}

function expected(name: string): Record<string, any> {
  return messages[name].decoded
}

describe('the fixture itself', () => {
  it('was generated for the protocol version this build speaks', () => {
    // A fixture from a different protocol version would make every test below pass
    // against the wrong contract, which is worse than having no tests.
    expect(fixture.protocolVersion).toBe(PROTOCOL_VERSION)
  })
})

describe('decoding what the hub sends', () => {
  it('reads a machine list, including a machine with no sessions', () => {
    const machines = decodeMachineList(wire('machineList'))
    const want = expected('machineList').machines as any[]

    expect(machines).toHaveLength(want.length)

    machines.forEach((machine, i) => {
      expect(machine.machineId).toBe(want[i].machineId)
      expect(machine.displayName).toBe(want[i].displayName)
      expect(machine.os).toBe(want[i].os)
      expect(machine.agentVersion).toBe(want[i].agentVersion)
      expect(machine.online).toBe(want[i].online)
      expect(machine.sessions).toHaveLength(want[i].sessions.length)
    })
  })

  it('reads a session, including its arguments and working directory', () => {
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0]

    expect(session.sessionId).toBe(want.sessionId)
    expect(session.program).toBe(want.program)
    expect(session.args).toEqual(want.args)
    expect(session.cwd).toBe(want.cwd)
    expect(session.cols).toBe(want.cols)
    expect(session.rows).toBe(want.rows)
    expect(session.displayName).toBe(want.displayName)
    expect(session.awaitingInput).toBe(want.awaitingInput)
  })

  /**
   * The C# side renders the enum as a number in the fixture's `decoded` block —
   * that is `System.Text.Json` describing a C# enum, not what MessagePack put on the
   * wire. The bytes carry the *name*, which is what the decoder has to read, so this
   * asserts the name and cross-checks the ordinal the C# enum declares.
   */
  it('reads the CLI type as the name the wire actually carries', () => {
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]

    expect(session.cliType).toBe('ClaudeCode')
    expect(expected('machineList').machines[0].sessions[0].cliType).toBe(3)
  })

  it('distinguishes structured agent chats from terminals', () => {
    const sessions = decodeMachineList(wire('machineList'))[0].sessions

    expect(sessions[0].kind).toBe('Terminal')
    expect(sessions[1].kind).toBe('AgentChat')
    expect(sessions[1].program).toBe('GitHub Copilot')
  })

  it('calls a session Generic when the type is missing or unknown', () => {
    // A version 1 agent sends a nine-element session; a later one could send a type
    // this build has never heard of. Both mean "nobody has said", not a crash.
    const raw = wire('sessionOpened') as unknown[]
    const session = raw[1] as unknown[]

    expect(decodeSessionOpened([raw[0], session.slice(0, 9)]).session.cliType).toBe('Generic')
    expect(
      decodeSessionOpened([raw[0], [...session.slice(0, 9), 'Emacs']]).session.cliType,
    ).toBe('Generic')
  })

  it('reads a session being corrected', () => {
    const updated = decodeSessionUpdated(wire('sessionUpdated'))
    const want = expected('sessionUpdated')

    expect(updated.machineId).toBe(want.machineId)
    expect(updated.session.sessionId).toBe(want.session.sessionId)
    expect(updated.session.cliType).toBe('CopilotCli')
  })

  it('reads the name the user gave a session, and whether they pinned it', () => {
    const updated = decodeSessionUpdated(wire('sessionUpdated'))
    const want = expected('sessionUpdated')

    expect(updated.session.customName).toBe(want.session.customName)
    expect(updated.session.pinned).toBe(want.session.pinned)
  })

  it('treats a session from a hub that predates renaming as unnamed and unpinned', () => {
    // The two fields were appended, so an older hub sends a ten-element session.
    // Reading past the end has to land on "nobody renamed it", not on undefined
    // reaching a row that then renders the string "undefined".
    const raw = wire('sessionUpdated') as unknown[]
    const session = raw[1] as unknown[]

    const decoded = decodeSessionUpdated([raw[0], session.slice(0, 10)]).session

    expect(decoded.customName).toBeNull()
    expect(decoded.pinned).toBe(false)
  })

  it('recovers the real instant a session started, not the sender wall clock', () => {
    // The fixture deliberately uses a +03:00 offset. A decoder that reads only the
    // first element of the DateTimeOffset pair passes on a UTC machine and is three
    // hours wrong here.
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0].startedAt as string

    expect(session.startedAt.toISOString()).toBe(new Date(want).toISOString())
  })

  it('falls back to the program name when a session has no display name', () => {
    const { session } = decodeSessionOpened(wire('sessionOpened'))

    expect(expected('sessionOpened').session.displayName).toBeNull()
    expect(session.displayName).toBe('pwsh')
  })

  it('reads a machine coming online', () => {
    const machine = decodeMachineOnline(wire('machineOnline'))

    expect(machine.machineId).toBe(expected('machineOnline').machine.machineId)
    expect(machine.online).toBe(true)
    expect(machine.sessions).toEqual([])
  })

  it('reads a machine going offline', () => {
    expect(decodeMachineOffline(wire('machineOffline'))).toBe(
      expected('machineOffline').machineId,
    )
  })

  it('reads a session opening', () => {
    const opened = decodeSessionOpened(wire('sessionOpened'))
    const want = expected('sessionOpened')

    expect(opened.machineId).toBe(want.machineId)
    expect(opened.session.sessionId).toBe(want.session.sessionId)
    expect(opened.session.args).toEqual([])
  })

  it('reads a session closing, with its exit code', () => {
    const closed = decodeSessionClosed(wire('sessionClosed'))
    const want = expected('sessionClosed')

    expect(closed.machineId).toBe(want.machineId)
    expect(closed.sessionId).toBe(want.sessionId)
    expect(closed.exitCode).toBe(want.exitCode)
  })

  it('reads terminal output, keeping the bytes exactly as sent', () => {
    const output = decodeTerminalOutput(wire('terminalOutput'))
    const want = expected('terminalOutput')

    expect(output.sessionId).toBe(want.sessionId)
    expect(output.seq).toBe(want.seq)
    // The enum travels as its name. A decoder that expects a number reads every
    // snapshot as a delta and never clears the screen.
    expect(output.kind).toBe('Snapshot')
    expect(Array.from(output.data)).toEqual([0x1b, 0x5b, 0x32, 0x4a, 0x68, 0x69, 0x0d, 0x0a])
  })

  it('reads a sequence number well past 32 bits', () => {
    // Long-running sessions overflow an int, and a decoder that truncates would
    // silently reorder output.
    expect(decodeTerminalOutput(wire('terminalOutput')).seq).toBe(4294967297)
  })

  it('reads an awaiting-input notice and its hint', () => {
    const awaiting = decodeAwaitingInput(wire('sessionAwaitingInput'))
    const want = expected('sessionAwaitingInput')

    expect(awaiting.machineId).toBe(want.machineId)
    expect(awaiting.sessionId).toBe(want.sessionId)
    expect(awaiting.hint).toBe(want.hint)
  })

  it('reads explicit attention state', () => {
    const attention = decodeSessionAttention(wire('sessionAttention'))
    const want = expected('sessionAttention')

    expect(attention.machineId).toBe(want.machineId)
    expect(attention.sessionId).toBe(want.sessionId)
    expect(attention.awaitingInput).toBe(true)
    expect(attention.hint).toBe(want.hint)
  })

  it('reads typed transcript events and permission options', () => {
    const transcript = decodeChatTranscript(wire('chatTranscript'))
    const want = expected('chatTranscript')

    expect(transcript.sessionId).toBe(want.sessionId)
    expect(transcript.seq).toBe(want.seq)
    expect(transcript.kind).toBe('Snapshot')
    expect(transcript.events.map((event) => event.kind)).toEqual([
      'UserMessage',
      'ToolCall',
      'Permission',
    ])
    expect(transcript.events[2].permissionRequestId).toBe('req-1')
    expect(transcript.events[2].options).toEqual([
      { optionId: 'allow-once', name: 'Allow once', kind: 'allow_once' },
      { optionId: 'reject-once', name: 'Deny', kind: 'reject_once' },
    ])
  })

  it('reads a token expiry', () => {
    const expiresAt = decodeTokenExpiring(wire('tokenExpiring'))

    expect(expiresAt.toISOString()).toBe(
      new Date(expected('tokenExpiring').expiresAt as string).toISOString(),
    )
  })

  it('reads an error, and its null session id', () => {
    const error = decodeError(wire('error'))
    const want = expected('error')

    expect(error.code).toBe(want.code)
    expect(error.message).toBe(want.message)
    expect(error.sessionId).toBeNull()
  })
})

describe('encoding what we send the hub', () => {
  // Encoding is checked against the same fixture from the other direction: the C#
  // test recorded the bytes its own deserialiser accepts, so producing the same
  // array shape is the whole requirement. A JS object here would encode as a
  // MessagePack map, which the C# formatter for a keyed type cannot read at all.

  function shape(name: string): unknown[] {
    const value = wire(name)
    expect(Array.isArray(value)).toBe(true)
    return value as unknown[]
  }

  it('sends a handshake the hub can read', () => {
    const [version, client] = shape('clientHandshakeRequest')

    expect(encodeClientHandshake(version as number, client as string)).toEqual([version, client])
    expect(version).toBe(PROTOCOL_VERSION)
  })

  it('sends an attach request, including a null last sequence', () => {
    const want = shape('attachSessionRequest')

    expect(encodeAttachSession(want[0] as string, want[1] as string, 80, 24, null)).toEqual(want)
  })

  it('sends a detach request', () => {
    const want = shape('detachSessionRequest')

    expect(encodeDetachSession(want[0] as string)).toEqual(want)
  })

  it('sends input as raw bytes', () => {
    const want = shape('sendInputRequest')

    const encoded = encodeSendInput(want[0] as string, new Uint8Array([0x64, 0x69, 0x72, 0x0d]))

    expect(encoded[0]).toBe(want[0])
    expect(Array.from(encoded[1] as Uint8Array)).toEqual(Array.from(want[1] as Uint8Array))
  })

  it('sends a resize', () => {
    const want = shape('resizeTerminalRequest')

    expect(encodeResizeTerminal(want[0] as string, want[1] as number, want[2] as number)).toEqual(
      want,
    )
  })

  it('sends an interrupt', () => {
    const want = shape('interruptSessionRequest')

    expect(encodeInterruptSession(want[0] as string)).toEqual(want)
  })

  it('sends a structured chat message', () => {
    const want = shape('sendChatMessageRequest')

    expect(encodeSendChatMessage(want[0] as string, want[1] as string)).toEqual(want)
  })

  it('sends a permission response', () => {
    const want = shape('respondChatPermissionRequest')

    expect(
      encodeRespondChatPermission(want[0] as string, want[1] as string, want[2] as string),
    ).toEqual(want)
  })

  it('sends a type correction as the name the hub validates', () => {
    const want = shape('setSessionTypeRequest')

    expect(want[1]).toBe('ClaudeCode')
    expect(encodeSetSessionType(want[0] as string, want[1] as CliType)).toEqual(want)
  })

  it('sends a rename, machine id first', () => {
    const want = shape('setSessionNameRequest')

    expect(encodeSetSessionName(want[0] as string, want[1] as string, want[2] as string)).toEqual(
      want,
    )
  })

  it('sends a cleared name as null, not as an empty string', () => {
    // The difference is the whole feature: null reveals the agent's own name again,
    // an empty string would leave the row with nothing to show.
    const want = shape('setSessionNameClearRequest')

    expect(want[2]).toBeNull()
    expect(encodeSetSessionName(want[0] as string, want[1] as string, null)).toEqual(want)
  })

  it('sends a pin', () => {
    const want = shape('setSessionPinnedRequest')

    expect(encodeSetSessionPinned(want[0] as string, want[1] as string, want[2] as boolean)).toEqual(
      want,
    )
  })
})
