import { describe, expect, it } from 'vitest'
import { decode } from '@msgpack/msgpack'

import fixture from './wire.fixture.json'
import { PROTOCOL_VERSION } from './methods'
import {
  decodeAwaitingInput,
  decodeError,
  decodeMachineList,
  decodeMachineOffline,
  decodeMachineOnline,
  decodeSessionClosed,
  decodeSessionOpened,
  decodeTerminalOutput,
  decodeTokenExpiring,
  encodeAttachSession,
  encodeClientHandshake,
  encodeDetachSession,
  encodeInterruptSession,
  encodeResizeTerminal,
  encodeSendInput,
} from './wire'

/**
 * The decoder against bytes the C# serializer actually produced.
 *
 * `wire.fixture.json` is generated by `tests/Protocol.Tests/WireContractTests.cs`,
 * which records both the bytes and the values they carry. Nothing here hand-copies
 * a constant from the C# side: every expectation is read out of the fixture's own
 * `decoded` block, so if a message's field order changes, the C# test fails on the
 * bytes and these fail on the values.
 */

type FixtureMessage = { type: string; base64: string; decoded: Record<string, unknown> }

const messages = fixture.messages as unknown as Record<string, FixtureMessage>

function wire(name: string): unknown {
  const entry = messages[name]
  expect(entry, `${name} is missing from the wire fixture`).toBeDefined()

  return decode(Uint8Array.from(atob(entry.base64), (c) => c.charCodeAt(0)))
}

function expected(name: string): Record<string, any> {
  return messages[name].decoded
}

describe('the fixture itself', () => {
  it('was generated for the protocol version this build speaks', () => {
    // A fixture from a different protocol version would make every test below pass
    // against the wrong contract, which is worse than having no tests.
    expect(fixture.protocolVersion).toBe(PROTOCOL_VERSION)
  })
})

describe('decoding what the hub sends', () => {
  it('reads a machine list, including a machine with no sessions', () => {
    const machines = decodeMachineList(wire('machineList'))
    const want = expected('machineList').machines as any[]

    expect(machines).toHaveLength(want.length)

    machines.forEach((machine, i) => {
      expect(machine.machineId).toBe(want[i].machineId)
      expect(machine.displayName).toBe(want[i].displayName)
      expect(machine.os).toBe(want[i].os)
      expect(machine.agentVersion).toBe(want[i].agentVersion)
      expect(machine.online).toBe(want[i].online)
      expect(machine.sessions).toHaveLength(want[i].sessions.length)
    })
  })

  it('reads a session, including its arguments and working directory', () => {
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0]

    expect(session.sessionId).toBe(want.sessionId)
    expect(session.program).toBe(want.program)
    expect(session.args).toEqual(want.args)
    expect(session.cwd).toBe(want.cwd)
    expect(session.cols).toBe(want.cols)
    expect(session.rows).toBe(want.rows)
    expect(session.displayName).toBe(want.displayName)
    expect(session.awaitingInput).toBe(want.awaitingInput)
  })

  it('recovers the real instant a session started, not the sender wall clock', () => {
    // The fixture deliberately uses a +03:00 offset. A decoder that reads only the
    // first element of the DateTimeOffset pair passes on a UTC machine and is three
    // hours wrong here.
    const session = decodeMachineList(wire('machineList'))[0].sessions[0]
    const want = expected('machineList').machines[0].sessions[0].startedAt as string

    expect(session.startedAt.toISOString()).toBe(new Date(want).toISOString())
  })

  it('falls back to the program name when a session has no display name', () => {
    const { session } = decodeSessionOpened(wire('sessionOpened'))

    expect(expected('sessionOpened').session.displayName).toBeNull()
    expect(session.displayName).toBe('pwsh')
  })

  it('reads a machine coming online', () => {
    const machine = decodeMachineOnline(wire('machineOnline'))

    expect(machine.machineId).toBe(expected('machineOnline').machine.machineId)
    expect(machine.online).toBe(true)
    expect(machine.sessions).toEqual([])
  })

  it('reads a machine going offline', () => {
    expect(decodeMachineOffline(wire('machineOffline'))).toBe(
      expected('machineOffline').machineId,
    )
  })

  it('reads a session opening', () => {
    const opened = decodeSessionOpened(wire('sessionOpened'))
    const want = expected('sessionOpened')

    expect(opened.machineId).toBe(want.machineId)
    expect(opened.session.sessionId).toBe(want.session.sessionId)
    expect(opened.session.args).toEqual([])
  })

  it('reads a session closing, with its exit code', () => {
    const closed = decodeSessionClosed(wire('sessionClosed'))
    const want = expected('sessionClosed')

    expect(closed.machineId).toBe(want.machineId)
    expect(closed.sessionId).toBe(want.sessionId)
    expect(closed.exitCode).toBe(want.exitCode)
  })

  it('reads terminal output, keeping the bytes exactly as sent', () => {
    const output = decodeTerminalOutput(wire('terminalOutput'))
    const want = expected('terminalOutput')

    expect(output.sessionId).toBe(want.sessionId)
    expect(output.seq).toBe(want.seq)
    // The enum travels as its name. A decoder that expects a number reads every
    // snapshot as a delta and never clears the screen.
    expect(output.kind).toBe('Snapshot')
    expect(Array.from(output.data)).toEqual([0x1b, 0x5b, 0x32, 0x4a, 0x68, 0x69, 0x0d, 0x0a])
  })

  it('reads a sequence number well past 32 bits', () => {
    // Long-running sessions overflow an int, and a decoder that truncates would
    // silently reorder output.
    expect(decodeTerminalOutput(wire('terminalOutput')).seq).toBe(4294967297)
  })

  it('reads an awaiting-input notice and its hint', () => {
    const awaiting = decodeAwaitingInput(wire('sessionAwaitingInput'))
    const want = expected('sessionAwaitingInput')

    expect(awaiting.machineId).toBe(want.machineId)
    expect(awaiting.sessionId).toBe(want.sessionId)
    expect(awaiting.hint).toBe(want.hint)
  })

  it('reads a token expiry', () => {
    const expiresAt = decodeTokenExpiring(wire('tokenExpiring'))

    expect(expiresAt.toISOString()).toBe(
      new Date(expected('tokenExpiring').expiresAt as string).toISOString(),
    )
  })

  it('reads an error, and its null session id', () => {
    const error = decodeError(wire('error'))
    const want = expected('error')

    expect(error.code).toBe(want.code)
    expect(error.message).toBe(want.message)
    expect(error.sessionId).toBeNull()
  })
})

describe('encoding what we send the hub', () => {
  // Encoding is checked against the same fixture from the other direction: the C#
  // test recorded the bytes its own deserialiser accepts, so producing the same
  // array shape is the whole requirement. A JS object here would encode as a
  // MessagePack map, which the C# formatter for a keyed type cannot read at all.

  function shape(name: string): unknown[] {
    const value = wire(name)
    expect(Array.isArray(value)).toBe(true)
    return value as unknown[]
  }

  it('sends a handshake the hub can read', () => {
    const [version, client] = shape('clientHandshakeRequest')

    expect(encodeClientHandshake(version as number, client as string)).toEqual([version, client])
    expect(version).toBe(PROTOCOL_VERSION)
  })

  it('sends an attach request, including a null last sequence', () => {
    const want = shape('attachSessionRequest')

    expect(encodeAttachSession(want[0] as string, want[1] as string, 80, 24, null)).toEqual(want)
  })

  it('sends a detach request', () => {
    const want = shape('detachSessionRequest')

    expect(encodeDetachSession(want[0] as string)).toEqual(want)
  })

  it('sends input as raw bytes', () => {
    const want = shape('sendInputRequest')

    const encoded = encodeSendInput(want[0] as string, new Uint8Array([0x64, 0x69, 0x72, 0x0d]))

    expect(encoded[0]).toBe(want[0])
    expect(Array.from(encoded[1] as Uint8Array)).toEqual(Array.from(want[1] as Uint8Array))
  })

  it('sends a resize', () => {
    const want = shape('resizeTerminalRequest')

    expect(encodeResizeTerminal(want[0] as string, want[1] as number, want[2] as number)).toEqual(
      want,
    )
  })

  it('sends an interrupt', () => {
    const want = shape('interruptSessionRequest')

    expect(encodeInterruptSession(want[0] as string)).toEqual(want)
  })
})
