<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Protocol\1RemoteCLI.Protocol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Lib.Net.Http.WebPush" Version="3.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.MessagePack" Version="8.0.28" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>OneRemoteCli.Hub</RootNamespace>
  </PropertyGroup>

</Project>
